"""
YouTube Video Summarizer
Fetches a YouTube transcript and generates AI-powered notes using BART-large-CNN.
"""

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled, NoTranscriptFound
import re
import os
import argparse
from datetime import datetime, timezone

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from tqdm import tqdm

MODEL_NAME = "facebook/bart-large-cnn"  # Trained specifically for summarization
CHUNK_SIZE = 1200
CHUNK_OVERLAP = 100
MAX_INPUT_TOKENS = 1024
MAX_SUMMARY_TOKENS = 200
NUM_BEAMS = 4
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(f"⚙️  Loading model '{MODEL_NAME}' on {DEVICE}...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME).to(DEVICE)
print("✅ Model loaded.\n")


def extract_video_id(url: str) -> str | None:
    """Extract the 11-character video ID from a YouTube URL."""
    match = re.search(r'(?:v=|youtu\.be/)([a-zA-Z0-9_-]{11})', url)
    return match.group(1) if match else None


def get_transcript(video_id: str) -> str:
    """Fetch the transcript for a given video ID."""
    try:
        api = YouTubeTranscriptApi()
        transcript = api.fetch(video_id)
        return " ".join([t.text for t in transcript])
    except TranscriptsDisabled:
        raise RuntimeError("Transcripts are disabled for this video.")
    except NoTranscriptFound:
        raise RuntimeError("No transcript found for this video.")
    except Exception as e:
        raise RuntimeError(f"Failed to fetch transcript: {e}")


def clean_transcript(text: str) -> str:
    """Clean raw YouTube auto-caption text."""
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'\b(um|uh|erm|ah|like,?)\b', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'\b(\w+)( \1)+\b', r'\1', text, flags=re.IGNORECASE)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def chunk_text(text: str, chunk_size: int = CHUNK_SIZE, overlap: int = CHUNK_OVERLAP) -> list[str]:
    """Split text into chunks with overlap."""
    sentences = re.split(r'(?<=[.?!\n])\s+', text)

    if len(sentences) <= 2 and len(text) > chunk_size:
        words = text.split()
        sentences = []
        for i in range(0, len(words), 40):
            sentences.append(" ".join(words[i:i + 40]))

    chunks, current_chunk = [], ""

    for sentence in sentences:
        if len(current_chunk) + len(sentence) + 1 < chunk_size:
            current_chunk += sentence + " "
        else:
            if current_chunk.strip():
                chunks.append(current_chunk.strip())
            if overlap > 0 and len(current_chunk) > overlap:
                current_chunk = current_chunk[-overlap:] + " " + sentence + " "
            else:
                current_chunk = sentence + " "

    if current_chunk.strip():
        chunks.append(current_chunk.strip())

    return chunks


def summarize_text(text: str) -> str:
    """Summarize text using BART-large-CNN."""
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_INPUT_TOKENS,
    ).to(DEVICE)

    with torch.no_grad():
        summary_ids = model.generate(
            **inputs,
            max_new_tokens=MAX_SUMMARY_TOKENS,
            num_beams=NUM_BEAMS,
            length_penalty=1.2,
            early_stopping=True,
            no_repeat_ngram_size=3,
            repetition_penalty=1.2,
        )

    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)


def save_notes(notes: list[str], final_summary: str, video_url: str, output_path: str):
    """Save the generated notes to a Markdown file."""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"# 📝 AI-Generated Video Notes\n\n")
        f.write(f"**Source:** {video_url}  \n")
        f.write(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  \n")
        f.write(f"**Model:** {MODEL_NAME}  \n\n")
        f.write("---\n\n")
        f.write("## Overview\n\n")
        f.write(f"{final_summary}\n\n")
        f.write("## Detailed Notes\n\n")
        for i, note in enumerate(notes, 1):
            f.write(f"{i}. {note}\n")
        f.write("\n---\n*Generated by YT Summarizer*\n")

    print(f"💾 Notes saved to: {output_path}")


def generate_video_notes(video_url: str, output_dir: str = "notes"):
    """Main pipeline: fetch transcript → clean → chunk → summarize → save."""
    print(f"\n🎬 Processing video: {video_url}")

    # 1. Extract video ID
    video_id = extract_video_id(video_url)
    if not video_id:
        print("❌ Invalid YouTube URL. Expected format: https://youtube.com/watch?v=XXXXXXXXXXX")
        return

    # 2. Fetch transcript
    print("🎧 Fetching transcript...")
    try:
        transcript = get_transcript(video_id)
    except RuntimeError as e:
        print(f"❌ {e}")
        return

    word_count = len(transcript.split())
    print(f"   ✅ Transcript fetched ({word_count:,} words)")

    # 3. Clean and chunk
    print("🧹 Cleaning transcript...")
    transcript = clean_transcript(transcript)
    chunks = chunk_text(transcript)
    print(f"🔪 Split into {len(chunks)} chunks (chunk_size={CHUNK_SIZE})")

    # 4. Summarize each chunk
    print("🧠 Generating summaries...")
    notes = []
    for i, chunk in enumerate(tqdm(chunks, desc="   Summarizing", unit="chunk")):
        try:
            summary = summarize_text(chunk)
            notes.append(summary)
        except Exception as e:
            print(f"\n   ⚠️ Failed on chunk {i+1}: {e}")
            notes.append(f"[Chunk {i+1} failed]")

    # 5. Generate overall summary
    print("📋 Generating overall summary...")
    combined = " ".join(notes)
    try:
        final_summary = summarize_text(combined)
    except Exception as e:
        print(f"   ⚠️ Overall summary failed: {e}")
        final_summary = "Overall summary could not be generated."

    # 6. Print results
    print("\n" + "=" * 50)
    print("📝 AI-GENERATED NOTES")
    print("=" * 50)
    print(f"\n📌 Overall Summary:\n   {final_summary}\n")
    print("📖 Detailed Notes:")
    for i, note in enumerate(notes, 1):
        print(f"   {i}. {note}")

    # 7. Save to file
    output_path = os.path.join(output_dir, f"{video_id}.md")
    save_notes(notes, final_summary, video_url, output_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate AI notes from a YouTube video transcript.")
    parser.add_argument("url", nargs="?", help="YouTube video URL")
    parser.add_argument("-o", "--output-dir", default="notes", help="Directory to save notes (default: notes/)")
    args = parser.parse_args()

    url = args.url or input("Paste YouTube URL: ")
    generate_video_notes(url, output_dir=args.output_dir)
